spring.application.name=pixpay

server.port=8080

comunication.external-api.authorizer-url=https://util.devi.tools/api/v2/authorize
comunication.external-api.notify-transfer-url=https://util.devi.tools/api/v1/notify

jwt.private.key=classpath:app.key
jwt.public.key=classpath:app.pub

app.pagination.default-size:25

spring.datasource.url=jdbc:postgresql://db:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=broker:9092

app.redis.sentinel.master=mymaster
app.redis.sentinel.nodes=sentinel-1:26379,sentinel-2:26379,sentinel-3:26379
app.redis.sentinel.password=${REDIS_PASSWORD}
app.redis.sentinel.timeout-seconds=2
app.redis.sentinel.ttl-minutes=5

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api/docs
springdoc.override-with-generic-response=false
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha

management.tracing.sampling.probability=1.0
management.otlp.metrics.export.url=http://grafana-lgtm:4318/v1/metrics
management.opentelemetry.tracing.export.otlp.endpoint=http://grafana-lgtm:4318/v1/traces
management.opentelemetry.logging.export.otlp.endpoint=http://grafana-lgtm:4318/v1/logs
logging.level.com.desafio.pixpay=DEBUG
logging.level.org.springframework.boot.actuator.autoconfigure.opentelemetry=DEBUG
