events { 
    worker_connections 1024;
}

http {
    
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 15;

    # DNS interno do Docker
    resolver 127.0.0.11 valid=5s;

    # Configuração de Rate limiting: 20 requests por segundo
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=20r/s;

    upstream backend_pool {
        server backend-app:8080;
        keepalive 32;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            limit_req zone=api_limit burst=20 nodelay;
            limit_req_status 429;

            # 1. Trata a requisição OPTIONS (Preflight) do Angular
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' $http_origin always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
                add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, Cache-Control, Accept, Origin, X-Requested-With' always;
                add_header 'Access-Control-Allow-Credentials' 'true' always;
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain; charset=utf-8';
                add_header 'Content-Length' 0;
                return 204;
            }

            # 2. Cabeçalhos aplicados para as requisições normais (GET, POST, etc.)
            add_header 'Access-Control-Allow-Origin' $http_origin always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, Cache-Control, Accept, Origin, X-Requested-With' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;

            proxy_pass http://backend_pool;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            
            proxy_connect_timeout 2s;
            proxy_read_timeout 10s;
            proxy_next_upstream_tries 1;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
